import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <main className="w-full h-full">
            <Providers>
              <Navbar />
              {children}
            </Providers>
          </main>
      </body>
    </html>
  );
}
